### ISSUE TITLE
Impoting all of data

### ISSUE THREAD

**Issue by manindertaggar** [inventaire/wikidata-subset-search-engine#1]
how can i insert all of data to elastic search so that i can can wikidata object id by its title

**Comment by maxlath** [comment]
If you want to work with all Wikidata data, and not a subset of it, why not using directly the [Wikidata API](https://www.wikidata.org/w/api.php)? This project assumes that you are working with subsets, to which will be associated type names (in my case, `genres`, `movements`, `publishers`, `series`, etc.)
