### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by davidsbatista** [inventaire/wikidata-subset-search-engine#14]
not actually an issue, rather a question, is there a Docker image available for this entities-search-engine?

**Comment by maxlath** [comment]
no, but it could be easy to build one locally, with a dockerfile looking something like:
```dockerfile
FROM node:12-alpine
RUN npm install --production
CMD [ "npm", "start" ]
```
This would start a server with default config:
* listening to port `3213`
* expecting to find ElasticSearch on port `9200`

**Comment by jum-s** [comment]
Actually there is a dockerfile on https://github.com/inventaire/docker-inventaire but it needs some update since the entities-search-engine is now decaffeinated

**Comment by davidsbatista** [comment]
I could start having a look into it, but I'm unexperienced with NodeJS, can you give me some rough guidelines on what's needed ?

**Comment by jum-s** [comment]
If you are familiar with Docker, you might not need much knowledge about node. The [readme](https://github.com/inventaire/docker-inventaire/blob/master/README.md) is supposed to document the process of setting up an inventaire local environement (which include the entities search engine). If you have questions on any unclear point, we'll gladly answer it.

**Comment by davidsbatista** [comment]
I started by first just trying to run the Docker image you pointed, managed to run everything up to the

`docker-compose up -d`

the docker containers are running but it seems to be that there's no port mapping, I can't access anything

`http://127.0.0.1:9200/` -> ElasticSearch
`http://127.0.0.1:3006/` -> inventaire

running `docker ps` I see 4 containers
 
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
14e827e3818e        docker-inventaire_inventaire               "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes                           docker-inventaire_inventaire_1
796d2d02c51c        elasticsearch:2.4                          "/docker-entrypoint.…"   11 minutes ago      Up 11 minutes                           docker-inventaire_elasticsearch_1
869bd91a3ac9        couchdb:1.7.1                              "tini -- /docker-ent…"   11 minutes ago      Up 11 minutes                           docker-inventaire_couch_1
137fce0ab0f3        docker-inventaire_entities-search-engine   "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes                           docker-inventaire_entities-search-engine_1
```

but no ports mapping. It's strange because the mappings seem to be defined in `docker-compose.yml`

Any idea of what might be wrong?

**Comment by davidsbatista** [comment]
I'm now trying to investigate why the entities-search-engine doesn't start; can you anyone point where to fix this Node dependency? (I'm not familiar with Node at all)

```
20:16 $ docker run docker-inventaire_entities-search-engine
module.js:550
    throw err;
    ^

Error: Cannot find module '/node_modules/coffee-script/bin/coffee'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
