### ISSUE TITLE
import entities in ES with all the claims 

### ISSUE THREAD

**Issue by fracet** [inventaire/wikidata-subset-search-engine#6]
Hi
I am trying to create an ES instance to search for music bands, but I'd like the results to return all claims related to a band. Basically, when searching for "Metallica" I'd like our local ES instance to return the same amount of data as this api query https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&ids=Q15920

I am using this command to do the first import:
`cat latest-all.json.gz | gzip -d | wdfilter --keep id,type,labels,descriptions,aliases,claims,sitelinks --claim P31:Q215380 | import_to_elastic music`

As far as I can tell, wdfilter is doing its part of the job and extracting the full entities (I tested it on its own and the output seemed more complete than what I could see in the ES response), but then import_to_elastic seems to filter that and remove all the claims before inserting them in the ES index.

Is there a way to achieve the result I am looking for?

Thanks!

BR
Francesco

**Comment by maxlath** [comment]
hello Francesco!

yes, this can be done by editing your version of [`./lib/format_entity.coffee`](https://github.com/inventaire/entities-search-engine/blob/5e1de2d/lib/format_entity.coffee#L31):

from:
```coffee
  if needSimplification
    entity.labels = simplify.labels entity.labels
    entity.aliases = simplify.aliases entity.aliases
    entity.descriptions = simplify.descriptions entity.descriptions

  # Saving space by not indexing claims
  delete entity.claims
```

to something like:
```coffee
  if needSimplification
    entity.labels = simplify.labels entity.labels
    entity.aliases = simplify.aliases entity.aliases
    entity.descriptions = simplify.descriptions entity.descriptions
    entity.claims = simplify.claims entity.claims, {
      # see https://github.com/maxlath/wikidata-sdk/blob/master/docs/simplify_claims.md#options
      keepQualifiers: true,
      keepReferences: true,
      keepIds: true,
      keepHashes: true,
      keepTypes: true
    }
```

**Comment by fracet** [comment]
Awesome... worked like a charm.

Thank you very much for your help and for this great tool!
